-- CreateTable
CREATE TABLE `newsticker` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `message` MEDIUMTEXT NOT NULL,
    `icon` VARCHAR(50) NOT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
